FROM nginx:alpine

COPY src/ /var/www/html/

COPY deployment/default.conf /etc/nginx/conf.d/default.conf.temp

COPY deployment/05-docker-entrypoint.sh /docker-entrypoint.d/05-docker-entrypoint.sh 
RUN chmod +x /docker-entrypoint.d/05-docker-entrypoint.sh