services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - php-fpm
    environment:
      - PHP_CONTAINER_NAME=${PHP_CONTAINER_NAME}

  php-fpm:
    container_name: ${PHP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    env_file:
      - .env

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    # Remove the following line later
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    command: "--init-file /docker-entrypoint-initdb.d/schema.sql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - .mysql-data:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql