FROM php:8.1-fpm

RUN apt-get update && apt-get upgrade -y

RUN docker-php-ext-install pdo_mysql

# Install composer && git
RUN apt-get install -y git
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Copy source code
COPY ./src /var/www/html

# Set working directory
WORKDIR /var/www/html

# Run composer install
RUN composer install